# Generated by Django 4.0.3 on 2022-04-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=30)),
                ('obs_message', models.CharField(max_length=300, null=True)),
                ('situation', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done')], default='Pending', max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flavour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.flavor')),
            ],
        ),
    ]
