# Generated by Django 4.0.3 on 2022-04-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flavor',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='static/img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='situation',
            field=models.CharField(choices=[('Done', 'Done'), ('Pending', 'Pending')], default='Pending', max_length=30, null=True),
        ),
    ]
