# Generated by Django 4.0.3 on 2022-04-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_flavor_price_alter_flavor_cover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido',
            new_name='Order',
        ),
    ]
